### ISSUE TITLE
Need a method to specify which tests of a test suite to run (or not run)

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/compass#114]
It would be good to have a way for a user to alter the tests in a test suite after setup without having to edit the code and setup again.

@mark-petersen [wrote](https://github.com/MPAS-Dev/compass/pull/104#issuecomment-836809844):
> One of my common workflows is to run the full nightly regression suite once, then rerun it with other compilers or debug, openmp settings, but turn off the QU240 mesh and init to save time. Is there a way to do that? I think this PR does not address omitting a test case from a suite altogether.

**Comment by xylar** [comment]
One possibility is to copy the text file that lists the test cases in the suite (e.g. `nightly.txt`) to the work directory.  Users could then alter the file to remove (or comment out?) tests they don't want to run.  Then, when `compass run` gets called, it would only run tests in the list.  If a user added a test that hasn't been set up, we would need to issue an error (or we could get fancy and add setup the test case on the fly!).

**Comment by xylar** [comment]
@mark-petersen, BTW, with my recent changes to how mask are handled, the QU240 mesh step only takes 38 seconds (at least on my laptop) which is likely comparable to the time than it will take you to alter the config file for the `mesh` test case to remove the `mesh` step.  So my guess is that this particular optimization simply isn't needed anymore.

**Comment by mark-petersen** [comment]
@xylar, let's close this. I think #104 addresses it, and as you said I can make extra suites on the fly.

**Comment by xylar** [comment]
@mark-petersen, does that mean you also want to close #115?
