### ISSUE TITLE
enthalpy benchmark A failing due to halo size

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/compass#116]
When running `enthalpy_benchmark/A`, the run fails and file `log.landice.0000.err` shows:

```
----------------------------------------------------------------------
Beginning MPAS-landice Error Log File for task       0 of       1
    Opened at 2021/05/12 14:57:41
----------------------------------------------------------------------
ERROR: MALI requires that config_num_halos >= 3.  (edgeMask calculations require it.)
ERROR: An error has occurred in landice_init_block.
CRITICAL ERROR: An error has occurred in li_core_init. Aborting...
Logging complete.  Closing file at 2021/05/12 14:57:41
```

This seems to be because of
https://github.com/MPAS-Dev/compass/blob/19a0dd0b5e7c2df7880f7df313275942fdb9c3b4/compass/landice/tests/enthalpy_benchmark/namelist.landice#L11
in combination with recent halo-related changes to `landice/develop`.

**Comment by matthewhoffman** [comment]
Close by https://github.com/MPAS-Dev/compass/pull/133
