### ISSUE TITLE
Add tags for E3SM meshes

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/compass#17]
I think it would be a really good idea to add git tags to specific commits as the place to go to reproduce specific E3SM meshes.  My idea for tag names would be like: `mesh_ECwISC30to60E2r1`, so `mesh_` and then the E3SM short name.

Thoughts?

**Comment by xylar** [comment]
@vanroekel, @matthewhoffman and @mark-petersen, would this work for you?  If so, I'll do this for all the E3SM v2 meshes we've created so far.

**Comment by matthewhoffman** [comment]
Yeah that makes sense to me.  So a key element is the `r1` piece that ties a COMPASS version to a specific incarnation of a mesh, right?  I don't see much need/use for tags in the compass repo, so I'm not concerned about tag-clutter from using them for this.

**Comment by xylar** [comment]
> I don't see much need/use for tags in the compass repo, so I'm not concerned about tag-clutter from using them for this.

Hmm, I think we will want to do releases of this repo each time we update the metapackage (and potentially a future python package for `compass` itself), so I think we will have a lot of version tags.  That's partly why I want the mesh tags to be clearly distinguishable from `compass` releases.

**Comment by mark-petersen** [comment]
I think having one tag for each official mesh name in E3SM is extremely helpful. Then we have the state of compass and MPAS-Model, and don't need to search through PRs or merge messages for it.  @xylar thanks for thinking of it.

The tag would go to the merge commit, which is not part of the PR. We will just try to remember to add that as we go, for future PRs. We can always add it after the merge, of course.

**Comment by vanroekel** [comment]
I agree having a tag of compass for a specific production mesh sounds extremely useful and really important.

**Comment by xylar** [comment]
To Do:
- [ ] EC15to60E2r1
- [ ] EC30to60E2r2
- [ ] EC30to60E2r3
- [ ] EC15to60E2r4
- [ ] WC12to60E2r1
- [ ] WC14to60E2r2
- [ ] WC14to60E2r3
- [ ] SOwISC12to60E2r2
- [ ] SOwISC12to60E2r3
- [ ] ECwISC30to60E2r1

**Comment by xylar** [comment]
Okay, this is done (except for the final mesh, which hasn't yet been merged in #15).
