### ISSUE TITLE
`compass list -v` shows no output for "steps"

### ISSUE THREAD

**Issue by pbosler** [MPAS-Dev/compass#199]
Tried with 2 test cases.  "Steps" is empty in both.

```
compass list -v -n 39
path:          ocean/global_convergence/cosine_bell
name:          cosine_bell
MPAS core:     ocean
test group:    global_convergence
subdir:        cosine_bell
steps:
```

**Comment by xylar** [comment]
@pbosler, that's a trickier case because the steps aren't defined at construction for this test case but rather at setup depending on config options.  But I agree that the default steps should show up in this case.  I'll fix that tonight or tomorrow.  Thanks for pointing it out.

**Comment by pbosler** [comment]
Thanks, that makes sense.  I'm adding some convergence tests using the cosine bell test as a template, so that explains why I see no "steps" output for my new test cases, too.
