### ISSUE TITLE
Streams for comparison must be changed from single to double precision

### ISSUE THREAD

**Issue by mark-petersen** [MPAS-Dev/compass#235]
Currently, all streams produced by compass named output are single precision:
```
<stream name="output"
...
        precision="single"
```
This line must either changed to `"double"` or remove (double is default). 

All bit-for-bit tests that used the `output.nc` file for comparison has been only valid to ~7 digits, not 14 (restart file comparisons are still fine). This could have opened us to merging bugs that pass single precision, but luckily I've been testing with compass legacy for most PRs until early August, and compass legacy was correctly writing `output.nc` as double. I also redid the same tests summarized here today: https://github.com/E3SM-Project/E3SM/pull/4518#issuecomment-915759214 but with double precision, and the results were the same, indicating there were no bugs missed due to this single/double problem since August 5.

**Comment by mark-petersen** [comment]
In the `Registry.xml` file, single precision is specified for output streams here:

https://github.com/E3SM-Project/E3SM/blob/2ee584536bb3dbd12415708adf57d96e6c52ba35/components/mpas-ocean/src/Registry.xml#L1688-L1690

```
1688		<stream name="output"
1689				type="output"
1690				precision="single"
```
In compass legacy there is a output stream that is double precision, so that bfb comparisons are in double:
https://github.com/MPAS-Dev/compass/blob/ca2c5a980ec302e1979a576c8b4d981d4db369ac/ocean/templates/streams/output.xml#L3-L10

@xylar, I tried to fix this myself to make a pull request, but I don't understand how new compass generates streams. I am able to make temporary tests with single precision by removing line 1960 in the Registry.xml file and then recompiling.

**Comment by mark-petersen** [comment]
I can think of three ways to change to double precision:
1. Change the output stream in `Registry.xml` back to to double.
2. Have compass alter the output stream to double, as compass legacy does
3. add a stream to the `Registry.xml` named `comparison_output` or `output_double` or similar. 

When we changed E3SM output to single precision, we changed output.nc in Registry.xml to single because those are templates for longer runs, not just bit-for-bit tests. I think that argument still holds against (1).

**Comment by xylar** [comment]
I think 2 is the most reasonable approach. I will look into setting up a template for this in `compass/ocean/streams`.

**Comment by xylar** [comment]
@matthewhoffman, you may want to check if MALI is also affected by this issue.  My guess is your default output precision may still be double.

**Comment by mark-petersen** [comment]
This is solved by https://github.com/MPAS-Dev/compass/pull/237 for the ocean. @matthewhoffman if this is not a problem for you in MALI testing, we can close this issue.

**Comment by xylar** [comment]
I'm going to close this regardless.  If MALI has a similar issue, it's still separate from this one.

**Comment by matthewhoffman** [comment]
Thanks, @xylar and @mark-petersen .  Yes, we are using double precision everywhere.
