### ISSUE TITLE
Config provenenance tracking

### ISSUE THREAD

**Issue by matthewhoffman** [MPAS-Dev/compass#247]
It would be useful for debugging to have information on the provenance on where final config options came from.  This could be comments in the final config/namelist files indicating where those values originated like this example in  the final config:
```
velo_solver = 'FO'  # Applied from user config
advection = 'none' # Applied from test group config
...
```
 Or this could be a log (likely very long) that indicates each time a config option was updated and from which source that originated, like this example that would be its own separate file or part of the main log file:
```
-- Applying Test Group Config
   * Set 'advection' to 'none'
-- Applying User Config
   * Set 'velo_solver' to 'FO'
```

Whatever design was chosen, this could either always occur or only occur if some debug/verbose flag is specified.

**Comment by xylar** [comment]
Just a note to say that I haven't forgotten about this and will work on it in the next version of compass.

**Comment by xylar** [comment]
@matthewhoffman, I know you're away and not looking at GitHub but wanted to let you know that I made major headway on this today.  I have a way to parse config options that keep track of where they came from.  I just haven't yet written the info to the resulting config file yet.

In case you're curious:
https://github.com/xylar/compass/tree/customize_config_parser

**Comment by matthewhoffman** [comment]
@xylar , wow, that's great.  It sounds (and looks from your branch) that you've done all the heavy lifting already.  I like the design solution of wrapping the standard config parser to extend it's capabilities.
