### ISSUE TITLE
problem parsing '+' in sinfo

### ISSUE THREAD

**Issue by mark-petersen** [MPAS-Dev/compass#282]
PR #280 added this line:
https://github.com/MPAS-Dev/compass/blob/316f8579ff791fb88b3c3b76193ec34686f5a7a2/compass/parallel.py#L85

When I try this at the command line, it uses a '+' on the end on cori and blues:
```
blueslogin3:~$ sinfo --noheader   -o %c
16+
cori12$ sinfo --noheader   -o %c
64+
```
And the plus sign appears to cause the following error in all compass runs, including QU240/mesh:
```
cd to
/global/cscratch1/sd/mpeterse/runs/n/211206_test_QU240/ocean/global_ocean/QU240/mesh
(dev_compass_1.0.0) nid00994:mesh$ compass run
Traceback (most recent call last):
  File "/global/homes/m/mpeterse/miconda3/envs/dev_compass_1.0.0/bin/compass", line 33, in <module>
    sys.exit(load_entry_point('compass', 'console_scripts', 'compass')())
  File "/global/u2/m/mpeterse/repos/compass/pr/compass/__main__.py", line 62, in main
    commands[args.command]()
  File "/global/u2/m/mpeterse/repos/compass/pr/compass/run.py", line 308, in main
    run_test_case(args.steps, args.no_steps)
  File "/global/u2/m/mpeterse/repos/compass/pr/compass/run.py", line 216, in run_test_case
    set_cores_per_node(test_case.config)
  File "/global/u2/m/mpeterse/repos/compass/pr/compass/parallel.py", line 88, in set_cores_per_node
    cpus_per_node = _get_subprocess_int(args)
  File "/global/u2/m/mpeterse/repos/compass/pr/compass/parallel.py", line 97, in _get_subprocess_int
    value = int(value.decode('utf-8').strip('\n'))
ValueError: invalid literal for int() with base 10: '64+'
```
looks like we need to filter out the '+' in python. Could use a string.replace('+', '')

**Comment by mark-petersen** [comment]
This seemed to fix it:
```
vi compass/parallel.py
97     value = int(value.decode('utf-8').strip('\n').strip('+'))
```
I then get
```
/global/u2/m/mpeterse/repos/compass/pr/compass/parallel.py:91: UserWarning: Slurm found 64 cpus per node but config from mache was 32
  warnings.warn(f'Slurm found {cpus_per_node} cpus per node but '
```
which is probably expected, but otherwise it runs through the process.

**Comment by xylar** [comment]
@mark-petersen, thanks for reporting this.  The problem is more fundamental than just the `+`.  It turns out it is not reporting the information for the partition for the **current job** but for all partitions.  I need to figure out how to make it provide info for only the current partition or it will not be accurate.

**Comment by xylar** [comment]
Please reset to before #280 for now if that is a possibility for you (and rebase #273 to exclude that PR in your testing).
