### ISSUE TITLE
Coriolis parameter not being initialized in Global Ocean init step

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/compass#304]
Following difficulties that @ytakano3 is having spinning up his mesh focused on the Kuroshio Current, I tried rerunning the WC14 dynamic adjustment and got some pretty crazy results.

As an example, here is the SST in the initial condition:
![sst_ic](https://user-images.githubusercontent.com/4179064/150700182-44e58627-8dc1-46ae-94e5-42f6655b8cbb.png)
And here is the same after 30 days of dynamic adjustment:
![sst_30_days](https://user-images.githubusercontent.com/4179064/150700192-316cc057-661e-4668-b140-e130f5f944f4.png)
Note that SSTs reach 60 C in several coastal locations after 30 days!

Similarly, here is the temperature in layer 11 in the initial condition:
![temp_layer_11_ic](https://user-images.githubusercontent.com/4179064/150700208-5060ca65-8a21-46c5-92e5-1d800d4d3452.png)
and after 30 days:
![temp_layer_11_30_days](https://user-images.githubusercontent.com/4179064/150700215-e6e79b1d-4bac-4ef4-b5ba-38fa29bbe1d9.png)

**Comment by xylar** [comment]
The CFL number looks okay at a glance.  The final value is `0.176895880968517`, and it never appears to reach values above 0.2.

**Comment by xylar** [comment]
The results of my testing can be found here on Chrysalis/Anvil:
```
/lcrc/group/e3sm/ac.xylar/compass_1.0/chrysalis/test_20220123/test_wc14/ocean/global_ocean/WC14/
```

**Comment by xylar** [comment]
I believe I know a potential cause of these problems.  I believe `fCell`, `fEdge` and `fVertex` are never getting set.  This is because we set `config_expand_sphere = .false.` in this PR:
https://github.com/MPAS-Dev/compass/pull/95
However, it turns out that the subroutine where the radius of the Earth gets expanded is also the one where the Coriolis parameters get calculated:
https://github.com/E3SM-Project/E3SM/blob/85bd653607cdd1858fb4fe0f372a1936061fdc43/components/mpas-ocean/src/mode_init/mpas_ocn_init_spherical_utils.F#L195
https://github.com/E3SM-Project/E3SM/blob/85bd653607cdd1858fb4fe0f372a1936061fdc43/components/mpas-ocean/src/mode_init/mpas_ocn_init_spherical_utils.F#L222
https://github.com/E3SM-Project/E3SM/blob/85bd653607cdd1858fb4fe0f372a1936061fdc43/components/mpas-ocean/src/mode_init/mpas_ocn_init_spherical_utils.F#L241

These clearly need to be pulled out and put in their own subroutine.

**Comment by xylar** [comment]
Fortunately (?), we haven't created any new global meshes since that bug was introduced:
https://github.com/MPAS-Dev/compass/tags
So poor @ytakano3 and his Kuroshio mesh are the lucky first victims of this bug.

The fact that `f*` are all zeros in the initial condition also explains why a spin-up in E3SM didn't go any better than dynamic adjustment in standalone mode.

**Comment by xylar** [comment]
BTW, I really hate MPAS-Ocean init mode, just for the record.

**Comment by xylar** [comment]
@ytakano3, @jonbob and @maltrud, this is almost certainly the cause of the trouble you all have been having with @ytakano3's mesh.  I'm really sorry about that!

**Comment by xylar** [comment]
I opened https://github.com/E3SM-Project/E3SM/pull/4750 to fix this.

**Comment by ytakano3** [comment]
@xylar @jonbob and @maltrud , thank you for your support on fixing this! With your PR in E3SM-Project, I manage to make new initial conditions with the Coriolis parameter initialized this time. Dynamical adjustment worked, the files for E3SM looks good (also posted on E3SM #4750) so I started to move on to E3SM mode now for G-Case test. I will keep updated.

**Comment by mark-petersen** [comment]
To investigate the 60C temperature posted above, let’s concentrate on WC14 since that is where the error is most pronounced. It sounds like the points of comparison are:

1. WC14 on head of compass/legacy (Mark)
2. WC14 at PR merge point of compass/master for that test case. (Xylar)
3. WC14 on head of compass/master with expand_sphere on (Xylar)

That will help us pinpoint and do comparisons. The change could have been in the forward model, init mode, or compass flag settings.

**Comment by mark-petersen** [comment]
For (1) above the high temperature does not appear. To be exact, this is for
- current head of compass/legacy f4161e3d
- forward and init mode is MPAS-Dev/MPAS-Model ocean/develop branch, 2ce2729c2 April 28 2021 just before MPAS transplant.
- grizzly with these modules
```
module use /usr/projects/climate/SHARED_CLIMATE/modulefiles/all/; 
module unload python; 
source /usr/projects/climate/SHARED_CLIMATE/anaconda_envs/load_latest_compass.sh;
module load gcc/5.3.0 openmpi/1.10.5 netcdf/4.4.1 parallel-netcdf/1.5.0 pio/1.7.2;
```
Here are the results after initialization and spin-up, day 31. Many cells have `maxLevelCell=2`, and:
```
pwd
/lustre/scratch4/turquoise/mpeterse/runs/220125_legacy_head_gr_gfortran_openmp_WC1402/ocean/global_ocean/WC14/spin_up/test_final_settings/analysis_members
gr-fe1:analysis_members$ ncdump -v xtime globalStats.0001-01-01_00.00.00.nc |tail -n 2
  "0001-01-31_00:00:00                                             " ;
}
gr-fe1:analysis_members$ ncdump -v temperatureMax globalStats.0001-01-01_00.00.00.nc |tail -n 2
    30.3140239293587, 30.3140171341909 ;
```

**Comment by xylar** [comment]
@mark-petersen, I think we should probably create a new issue for keeping track of this because this issue seems to go beyond the coriolis parameter and whether we expand the earth sphere.  I'm not sure if that belongs in E3SM at all, probably in COMPASS for now at least.

**Comment by mark-petersen** [comment]
> @mark-petersen, I think we should probably create a new issue for keeping track of this

Note, the issue of high temperatures during spin-up is discussed in #308.
