### ISSUE TITLE
Consider copying rather than linking load script and executable

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/compass#345]
This would allow you to save a work directory and reuse it without having to keep the original compass branch.

**Comment by xylar** [comment]
@sbrus89 and I had the thought that we might have a config option and/or command-line flag to indicate that you want to copy the load scripts and executable.

A thought I had is that you would probably only want one copy of the executable and load script (maybe in the base of the work directory), and you would still have symlinks to those copies within individual test cases and steps.

**Comment by sbrus89** [comment]
@xylar, That sounds like an excellent idea. Maybe we should note that this is somewhat related to #346
