### ISSUE TITLE
Feature request: print test runtime during execution within a suite

### ISSUE THREAD

**Issue by matthewhoffman** [MPAS-Dev/compass#368]
It's great having the summary of test runtimes at the end of running a suite.  There are times I think it would be nice to also see the runtime of each individual test printed after the test completes.

e.g., go from this:
```
landice/greenland/fo_decomposition_test
  * step: 16proc_run
  * step: 32proc_run
  test execution:      SUCCESS
  test validation:     PASS
  baseline comparison: PASS
```
to
```
landice/greenland/fo_decomposition_test
  * step: 16proc_run
  * step: 32proc_run
  test execution:      SUCCESS
  test validation:     PASS
  baseline comparison: PASS
  test runtime: 00:18
```

This is not an important feature request and could be saved for a rainy day or a hackathon, assuming it's deemed worthwhile.

**Comment by xylar** [comment]
This would be something like a 5 minute change to make so it seems very much worth doing.  I have also wished for this.
