### ISSUE TITLE
Remove xtime from ISMIP6 ocean thermal forcing file from observations

### ISSUE THREAD

**Issue by trhille** [MPAS-Dev/compass#463]
@hollyhan @xylar, I noticed after https://github.com/MPAS-Dev/compass/pull/410 was merged that the `ocean_thermal_obs` test case includes an `xtime` variable for the ocean climatology, which I had to remove to start the run at any time other than `2015-01-01_00:00:00`. It would be better not to have `xtime` in the climatology forcing.

**Comment by xylar** [comment]
@hollyhan, is this something you can make a PR to fix?

**Comment by hollyhan** [comment]
@xylar , yes - I will take care of it!
