### ISSUE TITLE
Tides initial state trying to read nonexistent stream

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/compass#483]
In tides init, I'm seeing:
```
ERROR: Stream 'critical_passages' attempted to read non-existent file 'critical_passages.nc'
```
Example output is in:
```
/lcrc/group/e3sm/ac.xylar/compass_1.2/chrysalis/test_20221219/baseline/tides/ocean/tides/Icos7/init/initial_statelog.ocean.0000.err
```

**Comment by xylar** [comment]
@sbrus89, I don't think this is a real problem but it is disconcerting to get a lot of error files.

**Comment by xylar** [comment]
Removing these lines should solve it:
https://github.com/MPAS-Dev/compass/blob/master/compass/ocean/tests/tides/init/streams.init#L95-L102

**Comment by sbrus89** [comment]
@xylar - thanks for making an issue for this. @vanroekel told me he noticed the same errors. I'll create a PR to fix this.
