### ISSUE TITLE
intel-openmpi does not compile on chrysalis

### ISSUE THREAD

**Issue by mark-petersen** [MPAS-Dev/compass#506]
On the current compass `main` branch f126b1a1, the default chrysalis mpi library is `openmpi`:
```
./conda/configure_compass_env.py --conda ~/miconda3 --compiler intel
...
source load_dev_compass_1.2.0-alpha.4_chrysalis_intel_openmpi.sh
module list
Currently Loaded Modules:
  1) cmake/3.19.1-yisciec   3) intel/20.0.4-kodw73g    5) intel-mkl/2020.4.304-g2qaxzf   7) netcdf-c/4.4.1-ihoo4zq         9) parallel-netcdf/1.11.0-gvcfihh
  2) perl/5.32.0-bsnc6lt    4) openmpi/4.1.3-pin4k7o   6) hdf5/1.10.7-eewgp6v            8) netcdf-fortran/4.4.4-tplolxh  10) git/2.29.0-yshruxt
```
With that one loaded, and the head of E3SM f502d676a7, compile ends immediately with errors:

*with OPENMP*
```
make intel-mpi USE_PIO2=true OPENMP=true DEBUG=true
...
make[1]: Entering directory '/gpfs/fs1/home/ac.mpetersen/repos/E3SM/master/components/mpas-ocean'
Testing compiler for OpenMP support
/bin/sh: mpiicc: command not found
mpiicc does not support OpenMP - see INSTALL in top-level directory for more information
make[1]: *** [Makefile:857: openmp_test] Error 1
make[1]: Leaving directory '/gpfs/fs1/home/ac.mpetersen/repos/E3SM/master/components/mpas-ocean'
make: *** [Makefile:256: intel-mpi] Error 2
```

*without OPENMP*
```
make intel-mpi USE_PIO2=true OPENMP=false DEBUG=true
...
make[1]: Entering directory '/gpfs/fs1/home/ac.mpetersen/repos/E3SM/master/components/mpas-ocean'
Checking for a usable PIO library...
************ ERROR ************
Failed to compile a PIO test program
Please ensure the PIO environment variable is set to the PIO installation directory
************ ERROR ************
make[1]: *** [Makefile:880: pio_test] Error 1
make[1]: Leaving directory '/gpfs/fs1/home/ac.mpetersen/repos/E3SM/master/components/mpas-ocean'
make: *** [Makefile:256: intel-mpi] Error 2
```

But if I specify `impi` everything works:
```
./conda/configure_compass_env.py --conda ~/miconda3 --compiler intel --mpi impi
...
source load_dev_compass_1.2.0-alpha.4_chrysalis_intel_impi.sh
...
module list

Currently Loaded Modules:
  1) cmake/3.19.1-yisciec   3) intel/20.0.4-kodw73g           5) intel-mkl/2020.4.304-g2qaxzf   7) netcdf-c/4.4.1-qvxyzq2         9) parallel-netcdf/1.11.0-b74wv4m
  2) perl/5.32.0-bsnc6lt    4) intel-mpi/2019.9.304-tkzvizk   6) hdf5/1.8.16-se4xyo7            8) netcdf-fortran/4.4.4-rdxohvp
```
including compile with OPENMP true and false, DEBUG true or false, and running the nightly test suite.

**Comment by mark-petersen** [comment]
Going from `compass_1.2.0-alpha.2` to `compass_1.2.0-alpha.3` the default mpi library on chrysalis changed from `impi` to `openmpi`. But maybe I'm using the wrong compiler on `make intel-mpi`?

**Comment by xylar** [comment]
@mark-petersen, you need to replace `intel-mpi` with `ifort` in you make command for this configuration, see `MPAS make targest` in:
https://mpas-dev.github.io/compass/latest/developers_guide/machines/index.html#supported-machines

**Comment by xylar** [comment]
The `intel-mpi` target was specifically for Intel-MPI, not for Intel compilers in general.

> Going from `compass_1.2.0-alpha.2` to `compass_1.2.0-alpha.3` the default mpi library on chrysalis changed from `impi` to `openmpi`. But maybe I'm using the wrong compiler on `make intel-mpi`?

Indeed, I changed the default MPI to match E3SM (OpenMPI instead of Intel-MPI) as of `alpha.3`.

**Comment by mark-petersen** [comment]
Thanks. Silly me. I'll remember to check that in the future when launching my own compile instructions.
