### ISSUE TITLE
Issue running mpirun on one proc for a single_node system

### ISSUE THREAD

**Issue by mperego** [MPAS-Dev/compass#507]
When `parallel_system == single_node` and when `ntasks == 1`, the jobs are launched as, e.g.
`mpirun   ./landice_model`
instead of 
`mpirun -n 1 ./landice_model`

Unfortunately the former line executes the job using all the available slots, instead of just one rank  (at least on my machine).

@matthewhoffman pointed out that this is due to the following conditional
https://github.com/MPAS-Dev/compass/blob/main/compass/parallel.py#L154

@xylar Would it be possible to remove that line? That fixed the issue on my machine.

**Comment by xylar** [comment]
@mperego, oh, wow!  Sorry about that.  I think `srun` works differently but maybe not.  Anyway, I'll add `-n` regardless.

**Comment by mperego** [comment]
No worries! I was also surprised by how mpirun works when the number of tasks is not specified... maybe that behavior depends on some env variables.. or maybe it changed recently. Anyway, thanks for the fix!
