### ISSUE TITLE
Add a `--local_mache` argument to `configure_compass_env.py`

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/compass#520]
This would point to a local branch of `mache` to install with `pip install` and save a lot of time involved in building a mache conda package.

**Comment by xylar** [comment]
@matthewhoffman, thanks for prompting me think about this.

**Comment by matthewhoffman** [comment]
You're welcome, though I hadn't realized I had done so.  :)   Would this just be for testing updates to mache?  How is mache included when we run `configure_compass_env.py` to set up a new compass branch?

**Comment by xylar** [comment]
Yes, just for testing.

Mache is first installed in the `compass_install` conda environment, then that environment is activated to do the actual compass installation, which also includes mache.  So it's installed twice in 2 different environments.
