### ISSUE TITLE
method to run landice mesh generation tests without MALI build?

### ISSUE THREAD

**Issue by cwsmith** [MPAS-Dev/compass#528]
Hello,

Is there a cleaner way to run the landice mesh generation tests (i.e., `landice/antarctica/mesh_gen`) without a MALI build than the following hack (an empty MALI directory)?

```
$ mkdir -p /space/cwsmith/landice/compassAntarctica/MALI-Dev/components/mpas-albany-landice
$ cat config.compass  | grep landice
landice_database_root = /space/cwsmith/landice/compassAntarctica/MALI-Dev/components/mpas-albany-landice
$ compass setup -f config.compass -t landice/antarctica/mesh_gen -w $PWD
```

Thanks in advance.

**Comment by xylar** [comment]
@cwsmith, let me see what I can do to avoid this.  I agree, we don't want there to have to be a MALI directory (empty or otherwise) for this test case.

**Comment by xylar** [comment]
@cwsmith, I'm able to set up this test case with and empty `MALI-Dev` directory (i.e. no `components/mpas-albany-landice`).  I think I may have already fixed this a little while ago.  Can you verify that you have the latest version of the `main` branch when you see this issue?

**Comment by cwsmith** [comment]
@xylar Thank you. Running `compass --version` reports `compass 1.1.0` and it looks like the latest is [1.2.0*](https://github.com/MPAS-Dev/compass/blob/ef14b75fda3ff5dd2b667d302e4045acf9885a87/compass/version.py#L1).  I'll install the latest version and retest.

**Comment by xylar** [comment]
@cwsmith, are you installing compass from the conda package?  If so, v1.2.0 is still in development so you'll have to install from source following the quick start for developers:
https://mpas-dev.github.io/compass/latest/developers_guide/quick_start.html

**Comment by cwsmith** [comment]
@xylar Good catch.  I did install via the conda package.  Thanks for the link to the dev instructions.
