### ISSUE TITLE
Package incompatibility circularity

### ISSUE THREAD

**Issue by nickheavens-cgg** [MPAS-Dev/compass#664]
Dear compass developers,

1. Xylar kindly told me that I was probably the first person who is not an E3SM developer who wants to use compass. 

2. I don't need to run E3SM inside or outside compass, but I do need the latest stable versions of MPAS-Ocean and MPAS-Sea ice. I have a very nice PGF-based environment for building MPAS-Atmosphere (see here: [https://forum.mmm.ucar.edu/threads/successful-setup-for-mpas-a.13781/], which works just as well for building the maint2.1 E3SM versions of MPAS-Ocean and MPAS-Sea Ice (good work!). 

3. So I'm trying to do a port of compass on an unsupported machine, because I need to create my own meshes/input files for MPAS-Ocean and Sea Ice.

4. But I can't install the compass conda environment. Xylar kindly advised me to try the Developer instructions. But I can't do this using mpich (my preferred option), openmpi, and none.

The mpich issue is a package incompatibility issue when one runs: 

`./conda/configure_compass_env.py  --conda ~/mambaforge --mpi mpich`

One then finds in the bootstrap.log:

```
Could not solve for environment specs
The following packages are incompatible
├─ libnetcdf 4.8.1 mpi_mpich_* is installable with the potential options
│  ├─ libnetcdf 4.8.1 would require
│  │  └─ hdf5 >=1.10.6,<1.10.7.0a0 mpi_mpich_*, which can be installed;
│  ├─ libnetcdf 4.8.1 would require
│  │  └─ hdf5 >=1.12.2,<1.12.3.0a0 mpi_mpich_*, which can be installed;
│  └─ libnetcdf 4.8.1 would require
│     └─ hdf5 >=1.12.1,<1.12.2.0a0 mpi_mpich_*, which can be installed;
├─ mpas_tools 0.22.0  is installable with the potential options
│  ├─ mpas_tools 0.22.0 would require
│  │  └─ libnetcdf >=4.9.2,<4.9.3.0a0  but there are no viable options
│  │     ├─ libnetcdf 4.9.2 would require
│  │     │  └─ hdf5 >=1.14.1,<1.14.2.0a0 mpi_mpich_*, which conflicts with any installable versions previously reported;
│  │     └─ libnetcdf 4.9.2 conflicts with any installable versions previously reported;
│  ├─ mpas_tools 0.22.0 would require
│  │  └─ python >=3.11,<3.12.0a0 , which can be installed;
│  ├─ mpas_tools 0.22.0 would require
│  │  ├─ python >=3.8,<3.9.0a0 , which can be installed;
│  │  └─ python_abi 3.8.* *_cp38, which can be installed;
│  └─ mpas_tools 0.22.0 would require
│     ├─ python >=3.9,<3.10.0a0 , which can be installed;
│     └─ python_abi 3.9.* *_cp39, which can be installed;
├─ python 3.10**  is not installable because there are no viable options
│  ├─ python [3.10.0|3.10.10|...|3.10.9] conflicts with any installable versions previously reported;
│  └─ python [3.10.0|3.10.1|...|3.10.9] would require
│     └─ python_abi 3.10.* *_cp310, which conflicts with any installable versions previously reported;
└─ scorpio 1.4.1 mpi_mpich_* is installable and it requires
   └─ libnetcdf >=4.8.1,<4.8.2.0a0 mpi_mpich_*, which can be installed (as previously explained).
```
The main problem seems to be an inability to decide whether libnetcdf 4.8.1 or 4.9.2 should be used. This looks like a fundamental issue for the package, but I presume you've managed to make this work on the supported machines.

**Comment by xylar** [comment]
Hi @nickheavens-cgg, sorry about that!  I recently solved this problem in polaris, the successor to compass:
https://github.com/E3SM-Project/polaris/pull/103
I haven't had time tim back-port these changes to compass and I didn't think about the fact that that might cause you trouble.  I will try to take care of that in the next couple of days.

**Comment by nickheavens-cgg** [comment]
Dear Xylar,

Thanks so much! I didn't know about polaris.

Nick

**Comment by xylar** [comment]
@nickheavens-cgg, for you, polaris wouldn't be a good option yet.  We don't support the global ocean test group used to create meshes and initial conditions for E3SM.  But keep an eye on it, since we expect to port basically everything from compass to polaris by then end of the year.

**Comment by xylar** [comment]
I'm working on a fix for this right now.  I think it will be quite easy.

**Comment by nickheavens-cgg** [comment]
OK. Thanks!
