### ISSUE TITLE
drying_slope/1km/single_layer/loglaw fails

### ISSUE THREAD

**Issue by gcapodag** [MPAS-Dev/compass#722]
I am getting a runtime error in the forward step when running this test. This is the error:
```
At line 1074 of file mpas_ocn_vmix.F
Fortran runtime error: Index '0' of dimension 1 of array 'kineticenergycell' below lower bound of 1
```

It looks like those lines have been modified by @cbegeman with [this](https://github.com/E3SM-Project/E3SM/commit/bfd14dee36c8b285bdd508eb1888e5ea1403f46b) commit.

@cbegeman or @xylar, would you mind checking if you are getting the same failure? Thank you.

**Comment by cbegeman** [comment]
I'll look into it. This likely an E3SM issue, not a compass one. I'll confirm first, though. I have this note on L1072:
```
! For some reason we can use k-1 even when N=Nsurf
```
So it looks like I was aware that this could be a problem but didn't encounter that error. What machine, compiler combination are you using? Is debug on?

@xylar wasn't involved in that work so he doesn't need to look into it unless he wants to.

**Comment by xylar** [comment]
@cbegeman and @gcapodag, I'll leave this up to the 2 of you for now but ping me again if you would like my input.

**Comment by gcapodag** [comment]
`make gnu-cray DEBUG=true OPENMP=false`

**Comment by cbegeman** [comment]
@gcapodag Given the code freeze, I only opened a PR on ocean discussion https://github.com/E3SM-Ocean-Discussion/E3SM/pull/71. If you would like to use log-law drag in the meantime, I suggest cherry-picking this commit [c551420785c3be55010082325f691ad8331c7705](https://github.com/E3SM-Ocean-Discussion/E3SM/pull/71/commits/c551420785c3be55010082325f691ad8331c7705).

**Comment by cbegeman** [comment]
Migrated to https://github.com/E3SM-Project/E3SM/issues/6055
