### ISSUE TITLE
Major bug in `landice/antarctica/mesh_gen`

### ISSUE THREAD

**Issue by trhille** [MPAS-Dev/compass#729]
When running the `landice/antarctica/mesh_gen` case using default config settings, the mesh that is created is unusable:
![image](https://github.com/MPAS-Dev/compass/assets/17446278/a768cf44-6970-4a1a-9a7e-f8651142a593)

Thanks to @cwsmith for catching this!

**Comment by xylar** [comment]
Looks fine to me!

**Comment by trhille** [comment]
My initial thought was that that this was caused by the new cell culler, but the problem persists even when I checkout commit `51e65a5e342aa34bec97fb5478be7b75abc8be6e` and use `dev_compass_1.2.0-alpha.5`. In the [testing](https://github.com/MPAS-Dev/compass/pull/590#issuecomment-1503626739)section of the mesh generation refactor PR, I reported that the mesh was identical to the code before the refactor. However, there are numerous clean-up commits after that testing that could be responsible for the issue.

**Comment by trhille** [comment]
Further investigation reveals that `antarctica_8km_2020_10_20_floodFillMask.nc` contains only isolated pockets of ice, which indicates an issue with the flood fill.

**Comment by trhille** [comment]
Testing indicates that this was introduced by https://github.com/MPAS-Dev/compass/pull/590/commits/8b327bd224c27d3590e247002588469544701c51.

**Comment by xylar** [comment]
@trhille, very sorry about that!  I don't understand why it's a problem but let's revert it!
