### ISSUE TITLE
Sea ice trapped in isolated cells adjacent to ice shelves

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/compass#746]
In the SORRM 1950 control experiment, we're seeing 90,000 m of sea ice in one grid cell adjacent to the Ronne ice-shelf:
![image](https://github.com/MPAS-Dev/compass/assets/4179064/d30a4fac-e06d-4db1-b87e-4c7234f974db)
![image](https://github.com/MPAS-Dev/compass/assets/4179064/8d506489-81ae-4eaa-852d-752604cdea7a)

This completely corrupts the time series of sea-ice volume:
[iceVolume.pdf](https://github.com/MPAS-Dev/compass/files/13575154/iceVolume.pdf)

This appears to be because the cell has all land vertices, meaning it is completely isolated from a B-grid perspective.  I think this is because we widen channels where land is present but we don't modify `landIceMask` in the same way.  This needs to be fixed in the next SORRM and other Polar-focused meshes.

**Comment by proteanplanet** [comment]
We have trapped B-cells elsewhere on our meshes but they don't do that.  If coupler areas didn't quite add to 1, or if land runoff was influencing the result, we could see something like that. 90km of ice would suggest that physics are not controlling this result.

**Comment by proteanplanet** [comment]
One other thought:  Non-linear weightings have impacted certain freshwater quantities for V3, and weighting are being reverted to linear for precipitation.  Please check which type of weightings you are using, and perhaps try again once the weightings are set to linear as indicated for PR https://github.com/E3SM-Project/E3SM/pull/6094.

**Comment by xylar** [comment]
@proteanplanet,

This is the E3SM v2.1 SORRM 1950 control run, so nothing to do with E3SM v3.

**Comment by proteanplanet** [comment]
Thanks @xylar In that case, this problem may well be fixed with V3 - many bugs have been taken out.

**Comment by xylar** [comment]
Yep, let's hope so but we can also avoid creating these situations in the mesh in the first place when we make a new SORRM mesh.
