### ISSUE TITLE
Ability to view and alter steps within run command

### ISSUE THREAD

**Issue by mark-petersen** [MPAS-Dev/compass#80]
In the https://github.com/MPAS-Dev/compass/tree/legacy format, it is obvious to the user that the run steps are contained in run.py, and it is easy to copy from that script to the command line, or to only run parts of it.

In this new setup, it is not obvious how we see and alter the steps that occur in the command 
```
python -m compass run
```

See conversation at #76

**Comment by xylar** [comment]
I can see at least 2 ways to handle this, and we could do both:
1. Add command-line flags (e.g. `--steps` and `--no-steps`) where a user can explicitly list the steps they want to or don't want to run.
2. Add a config option (e.g. `[testcase]/steps_to_run = setup_mesh, run_model`) that would be initialized during test-case setup to the steps that get run by default but could be edited by a user.

The whole design is not meant to allow a user to just run parts of a step, so I don't think there's going to be any equivalent of copying and pasting pieces of the old `run.py` onto the command line.  If you think users would want to run parts of a step separately, they should be broken into individual steps.  Users are not meant to edit code.
