### ISSUE TITLE
Landice mismip+ mesh has incorrect boundary conditions at high resolution

### ISSUE THREAD

**Issue by trhille** [MPAS-Dev/compass#851]
For cell spacing ≤1km, the northern boundary of the mismip+ mesh has a `dirichletVelocityMask` multiple cells deep. Here is the issue on the 1km mesh:
![image](https://github.com/user-attachments/assets/408d34a4-4155-4c52-b190-a55c3f58231f)

and here is 500m:
![image](https://github.com/user-attachments/assets/57951291-b910-47c4-b9a3-522682721c16)

The effect on the velocity field is clearly visible for high resolution runs.
Presumably that is happening in this block of code, but I am not sure why:
https://github.com/MPAS-Dev/compass/blob/main/compass/landice/tests/mismipplus/setup_mesh.py#L452-L463

**Comment by andrewdnolan** [comment]
Thanks for catching this @trhille! 

Your correct about the offending lines. The issue has to do with using to large of relative tolerance in the floating point comparison. Specially looking at the equation in the [documentation of `np.isclose` ](https://numpy.org/doc/stable/reference/generated/numpy.isclose.html), where `b` would `y_max` (i.e.`8e4`) and our relative tolerance is `0.02`:
```
8e4 * 0.02 == 1600.0
```
which explains why this issue begins occurring at 1000m resolution.  

I'll open a PR to fix this.
